# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a93944ed43da9951264c4ab17739c217d2583c05a51e4b622c4387c6e4750cc0af2dee008a8bb9c3956c2d2b3f2ba82b3e4f11961289d242c05d9ba022d336e

test:
  secret_key_base: 3f04f39e7e7c616a19b403f9a55a8f436a8fe9f02fb7ec8e63e82d861e474b9f2ae85495d21ff4960c0aa336799156f8e9140bc2070a3d442228fc9ddb5b80e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
